name: Tests

on: push

jobs:
  php-tests:
    runs-on: ubuntu-latest

    name: PHP Static

    steps:
      - name: Checkout CPT Editor repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Display PHP environment
        run: |
          php -v
          composer check-platform-reqs

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --optimize-autoloader

      - name: Run 'phpcs' check
        run: composer test:style

      - name: Run 'phpstan' check
        run: composer test:static